-- MySQL Script generated by MySQL Workbench
-- 04/12/16 12:42:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema angular-rest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `angular-rest` ;

-- -----------------------------------------------------
-- Schema angular-rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `angular-rest` DEFAULT CHARACTER SET utf8 ;
USE `angular-rest` ;

-- -----------------------------------------------------
-- Table `angular-rest`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`customer` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `company_name1` VARCHAR(45) NULL,
  `company_name2` VARCHAR(45) NULL,
  `zip` VARCHAR(10) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-rest`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`job` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`job` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`job_id`),
  INDEX `job_customer_idx` (`customer_id` ASC),
  CONSTRAINT `job_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `angular-rest`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-rest`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`product_category` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`product_category` (
  `product_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`product_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-rest`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`product` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`product` (
  `product_id` INT NOT NULL,
  `product_category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `product_product_category_idx` (`product_category_id` ASC),
  CONSTRAINT `product_product_category`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `angular-rest`.`product_category` (`product_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-rest`.`product_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`product_rate` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`product_rate` (
  `product_rate_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `weight` DECIMAL(16,13) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`product_rate_id`),
  INDEX `product_rate_product_idx` (`product_id` ASC),
  CONSTRAINT `product_rate_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `angular-rest`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angular-rest`.`job_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular-rest`.`job_detail` ;

CREATE TABLE IF NOT EXISTS `angular-rest`.`job_detail` (
  `job_detail_id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NOT NULL,
  `product_rate_id` INT NOT NULL,
  PRIMARY KEY (`job_detail_id`),
  INDEX `job_detail_job_idx` (`job_id` ASC),
  INDEX `job_product_rate_idx` (`product_rate_id` ASC),
  CONSTRAINT `job_detail_job`
    FOREIGN KEY (`job_id`)
    REFERENCES `angular-rest`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_product_rate`
    FOREIGN KEY (`product_rate_id`)
    REFERENCES `angular-rest`.`product_rate` (`product_rate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `angular-rest`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`customer` (`customer_id`, `company_name1`, `company_name2`, `zip`, `city`) VALUES (120, 'Migros', NULL, '8031', 'Zurich');

COMMIT;


-- -----------------------------------------------------
-- Data for table `angular-rest`.`job`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`job` (`job_id`, `customer_id`) VALUES (1, 120);

COMMIT;


-- -----------------------------------------------------
-- Data for table `angular-rest`.`product_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`product_category` (`product_category_id`, `name`) VALUES (21, 'A');

COMMIT;


-- -----------------------------------------------------
-- Data for table `angular-rest`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`product` (`product_id`, `product_category_id`, `name`) VALUES (1, 21, 'Standardbrief');

COMMIT;


-- -----------------------------------------------------
-- Data for table `angular-rest`.`product_rate`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`product_rate` (`product_rate_id`, `product_id`, `weight`, `price`) VALUES (1, 1, 0.02, 1.0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `angular-rest`.`job_detail`
-- -----------------------------------------------------
START TRANSACTION;
USE `angular-rest`;
INSERT INTO `angular-rest`.`job_detail` (`job_detail_id`, `job_id`, `product_rate_id`) VALUES (1, 1, 1);
INSERT INTO `angular-rest`.`job_detail` (`job_detail_id`, `job_id`, `product_rate_id`) VALUES (2, 1, 1);

COMMIT;

