-- MySQL Script generated by MySQL Workbench
-- 04/12/16 12:42:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema angular-rest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table customer
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS customer (
  customer_id INT NOT NULL,
  company_name1 VARCHAR(45) NULL,
  company_name2 VARCHAR(45) NULL,
  zip VARCHAR(10) NULL,
  city VARCHAR(45) NULL,
  PRIMARY KEY (customer_id));


-- -----------------------------------------------------
-- Table job
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS job (
  job_id INT NOT NULL,
  customer_id INT NOT NULL,
  PRIMARY KEY (job_id),
  );


-- -----------------------------------------------------
-- Table product_category
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS product_category (
  product_category_id INT NOT NULL,
  name VARCHAR(45) NULL,
  PRIMARY KEY (product_category_id));


-- -----------------------------------------------------
-- Table product
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS product (
  product_id INT NOT NULL,
  product_category_id INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (product_id));


-- -----------------------------------------------------
-- Table product_rate
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS product_rate (
  product_rate_id INT NOT NULL,
  product_id INT NOT NULL,
  weight DECIMAL(16,13) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (product_rate_id));


-- -----------------------------------------------------
-- Table job_detail
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS job_detail (
  job_detail_id INT NOT NULL,
  job_id INT NOT NULL,
  product_rate_id INT NOT NULL,
  PRIMARY KEY (job_detail_id));

